[package]
name = "rustysecretsnif"
version = "0.1.0"
authors = []

[lib]
name = "rustysecretsnif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.15.1"
rustler_codegen = "0.15.1"
lazy_static = "0.2"
rusty_secrets = "0.0.2"
